# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: CompuTec.AppEngine.Preview
PackageVersion: 3.2607.6-rc-01
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
